---
title: Acknowledgements
---


# Compiled code

The 'broadcast' package would not have been possible without the fantastic [Rcpp](https://github.com/RcppCore/Rcpp) package, which 'broadcast' links to.  
Besides linking to the aforementioned 'Rcpp', no code from external libraries (like 'Numpy' or 'xtensor') were used in any way whatsoever.

&nbsp;

# Unit tests

The unit tests were facilitated using the impressive [tinytest](https://github.com/markvanderloo/tinytest) package.  
The coverage was measured and reported using the [covr](https://github.com/r-lib/covr) package.

&nbsp;

# Site resources

The website itself was put together using 'Quarto' version 1.3.

Most graphs on the website were created using the [tinyplot](https://github.com/grantmcdermott/tinyplot) package, and all tables were created using the [tinytable](https://github.com/vincentarelbundock/tinytable) package.  
Some of the icons were generated using the [fontawesome](https://github.com/rstudio/fontawesome) package.  
Nested lists were printed using the
[lobstr](https://github.com/r-lib/lobstr) package.

&nbsp;


