## Overloaded Operators {.unnumbered}


### Description

Sometimes broadcasting is needed in large mathematical expression,
involving multiple variables,
where precedence is of importance. <br />
For example in an expression like <code>x + y / z^y</code>. <br />
For such cases, you may want to overload the base operators. <br />
<br />
To that end, the 'broadcast' package provides the [broadcaster](broadcaster.qmd) class,
which comes with its own method dispatch for the base operators. <br />
If at least one of the 2 arguments of the base operators has the <code>broadcaster</code> class attribute,
and no other class (like <code>bit64</code>) interferes,
broadcasting will occur in the same manner as used in the various <code>bc.</code> - functions. <br />
<br />
The following arithmetic operators have a 'broadcaster' method:
+, -, *, /, ^, %%, %/% <br />
The following relational operators have a 'broadcaster' method:
==, !=, &lt;, &gt;, &lt;=, &gt;= <br />
And finally, the &amp; and | operators also have a 'broadcaster' method. <br />
<br />
The overloaded operators mimic the behaviour of the base 'R' operators accurately,
except they employ broadcasting, and they generally do not preserve attributes
(see broadcast_attributes for details on how the operators from 'broadcast' handle attributes). <br />
<br />
<br />



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE, collapse = TRUE, comment = NA}
library("broadcast")


# maths ====

x <- 1:10
broadcaster(x) <- TRUE

y <- 1:10
broadcaster(y) <- TRUE

x + y / x
x + 1 # mathematically equivalent to the above, since x == y
(x + y) / x
2 * x/x # mathematically equivalent to the above, since x == y

dim(x) <- c(10, 1)
dim(y) <- c(1, 10)

x + y / x
(x + y) / x

(x + y) * x


# relational operators ====
x <- 1:10
y <- array(1:10, c(1, 10))
broadcaster(x) <- TRUE
broadcaster(y) <- TRUE

x == y
x != y
x < y
x > y
x <= y
x >= y



```
