
## Attribute handling {.unnumbered}


### Description

The <code>bc.</code> functions and the overloaded operators generally do <b>not</b>
preserve attributes, unlike the base 'R' operators. <br />
<br />
Broadcasting often results in an object with more dimensions, larger dimensions,
and/or larger length than the original objects. <br />
Therefore, the <code>names</code>, <code>dimnames</code>, and <code>dim</code> attributes often no longer fit the new object. <br />
Moreover, some classes are only appropriate for certain dimensions or lengths. <br />
The implicit <code>matrix</code> class, for example, presumes an object to have exactly 2 dimensions. <br />
And the various classes provided by the 'bit' package have length-related attributes. <br />
So even class attributes cannot be guaranteed to hold for the resulting objects. <br />
<br />
However, the <code>bc.</code> functions and the overloaded operators
<b>always</b> preserve the &quot;broadcaster&quot; attribute,
as this is necessary to chain together broadcasted operations. <br />
Notice that this contrats with base 'R' in the following sense: <br />
In base 'R', logical (&amp;, |) and relational (==, !=, etc.) operators never preserve attributes,
whereas the broadcasted equivalents do preserve the &quot;broadcaster&quot; attribute. <br />
<br />
Unary operations (i.e. <code>+ x</code>, <code>- x</code>) return the original object,
with only the sign adjusted. <br />
<br />


