
## broadcast Package Overview {.unnumbered}


### Description

broadcast: <br />
'NumPy'-Like Broadcasted Operations for Atomic and Recursive Arrays with Minimal Dependencies. <br /> <br />

Implements efficient broadcasted operations for atomic and recursive arrays.

Besides linking to 'Rcpp', 'broadcast' does not use any external libraries in any way;
'broadcast' was essentially made from scratch and can be installed out-of-the-box.

The implementations available in 'broadcast' include, but are not limited to, the following:


<ol>
<li> Broadcasted element-wise operations on any 2 arrays;
they support a large set of
relational, arithmetic, Boolean, string, and bit-wise operations.

</li>
<li> A faster, more memory efficient, and broadcasted abind-like function, for binding arrays along an arbitrary dimension.

</li>
<li> Broadcasted ifelse-like, and apply-like functions.

</li>
<li> Casting functions, that cast subset-groups of an array to a new dimension, cast nested lists to dimensional lists, and vice-versa.

</li>
<li> A few linear algebra functions for statistics.

</li></ol>

The functions in the 'broadcast' package strive to minimize computation time and memory usage (which is not just good for efficient computing, but also for the environment).<br /> <br />

In the context of operations involving 2 (or more) arrays,
“broadcasting” refers to recycling array dimensions without allocating additional memory,
which is considerably faster and more memory-efficient
than R’s regular dimensions replication mechanism. <br /> <br />



### Links to Get Started


<ul>
<li> On-line Vignettes: <a href="https://tony-aw.github.io/broadcast/vignettes/a_readme.html">https://tony-aw.github.io/broadcast/vignettes/a_readme.html</a>

</li>
<li> GitHub main page: <a href="https://github.com/tony-aw/broadcast">https://github.com/tony-aw/broadcast</a>

</li>
<li> Reporting Issues or Giving Suggestions: <a href="https://github.com/tony-aw/broadcast/issues">https://github.com/tony-aw/broadcast/issues</a> <br /> <br />

</li></ul>



### Functions

<b>Broadcasted Operators</b> <br />
Base 'R' comes with relational (==, !=, etc.),
arithmetic (+, -, *, /, etc.), and logical/bit-wise (&amp;, |) operators. <br />
'broadcast' provides 2 ways to use these operators with broadcasting. <br />
<br />
The first (and simple) way is to use the [broadcaster](broadcaster.qmd) class,
which comes with it's own method dispatch for the above mentioned operators. <br />
This method support operator precedence, and for the average 'R' user,
this is sufficient. <br />
<br />
The second way is to use the large set of <code>bc.</code>- functions. <br />
These offer much greater control and more operators than the previous method,
and has less risk of running into conflicting methods. <br />
But it does not support operator precedence. <br />
<br />
More information about both methods can be found here: <br />
[broadcast_operators](aaa01_broadcast_operators.qmd). <br />
<br />

<b>Binding Arrays</b> <br />
'broadcast' provides the [bind_array](bind_array.qmd) function,
to bind arrays along an arbitrary dimension,
with support for broadcasting. <br />
<br />
The API of <code>bind_array()</code> is inspired by the fantastic
<code>abind::abind()</code> function
by Tony Plare &amp; Richard Heiberger (2016). <br />
But <code>bind_array()</code> differs considerably from <code>abind::abind</code>
in the following ways:


<ul>
<li> <code>bind_array()</code> allows for broadcasting,
while <code>abind::abind</code> does not support broadcasting.

</li>
<li> <code>bind_array()</code> is generally faster and more memory-efficient than <code>abind::abind</code>,
as <code>bind_array()</code> relies heavily on 'C' and 'C++' code.

</li>
<li> <code>bind_array()</code> differs from <code>abind::abind</code>
in that it can handle recursive arrays properly <br />
(the <code>abind::abind</code> function would unlist everything to atomic arrays,
ruining the structure).

</li>
<li> unlike <code>abind::abind</code>,
<code>bind_array()</code> only binds (atomic/recursive) arrays and matrices. <br />
<code>bind_array()</code>does not attempt to convert things to arrays when they are not arrays,
but will give an error instead. <br />
This saves computation time and prevents unexpected results.

</li>
<li> <code>bind_array()</code> has more streamlined naming options,
compared to <code>abind::abind</code>. <br />

</li></ul>

See [bind_array](bind_array.qmd). <br /><br />

<b>Casting Functions</b> <br />
'broadcast' provides several &quot;casting&quot; functions. <br />
These can facility complex forms of broadcasting that would normally not be possible. <br />
But these &quot;casting&quot; functions also have their own merit, beside empowering complex broadcasting. <br />
<br />
More information about the casting functions can be found here: <br />
[broadcast_casting](aaa02_broadcast_casting.qmd). <br />
<br />

<b>General functions</b> <br />
'broadcast' also comes with 2 general broadcasted functions:


<ul>
<li> [bc_ifelse](bc_ifelse.qmd): Broadcasted version of ifelse.

</li>
<li> [bcapply](bcapply.qmd): Broadcasted apply-like function. <br /> <br />

</li></ul>

<b>Other functions</b> <br />
'broadcast' provides
[type-casting](typecast.qmd) functions,
which preserve names and dimensions - convenient for arrays. <br />
<br />
'broadcast' also provides
[simple linear algebra functions for statistics](linear_algebra_stats.qmd). <br />
<br />
And 'broadcast' comes with some helper functions: <br />
[bc_dim](bc_dim.qmd), [ndim](ndim.qmd), [lst.ndim](ndim.qmd), [rep_dim](rep_dim.qmd). <br /> <br />



### Supported Structures

'broadcast' supports atomic/recursive arrays (up to 16 dimensions),
and atomic/recursive vectors. <br />
As in standard Linear Algebra Convention,
dimensionless vectors are interpreted as column-vectors in broadcasted array operations. <br />
<br />



### Author(s)

<strong>Author, Maintainer</strong>: Tony Wilkes <a href="mailto:tony_a_wilkes@outlook.com">tony_a_wilkes@outlook.com</a> (<a href="https://orcid.org/0000-0001-9498-8379">ORCID</a>)



### References

Plate T, Heiberger R (2016). <em>abind: Combine Multidimensional Arrays</em>. R package version 1.4-5, <a href="https://CRAN.R-project.org/package=abind">https://CRAN.R-project.org/package=abind</a>.

Harris, C.R., Millman, K.J., van der Walt, S.J. et al. <em>Array programming with NumPy</em>. Nature 585, 357–362 (2020). [doi:10.1038/s41586-020-2649-2](https://doi.org/10.1038/s41586-020-2649-2). (<a href="https://www.nature.com/articles/s41586-020-2649-2">Publisher link</a>).


