## Details on Casting Functions {.unnumbered}


### Description

'broadcast' provides several &quot;casting&quot; functions. <br />
These can facility complex forms of broadcasting that would normally not be possible. <br />
But these &quot;casting&quot; functions also have their own merit, beside empowering complex broadcasting. <br />
<br />
The following casting functions are available:


<ul>
<li> [acast](acast.qmd): <br />
casts group-based subset of an array into a new dimension. <br />
Useful for, for example, computing <b>grouped</b> broadcasted operations. <br />

</li>
<li> [cast_hier2dim](cast_hier2dim.qmd): <br />
casts a nested/hierarchical list into a dimensional list (i.e. recursive array). <br />
Useful because one cannot broadcast through nesting, but one <b>can</b> broadcast along dimensions.

</li>
<li> [cast_dim2hier](cast_dim2hier.qmd): <br />
casts a dimensional list into a nested/hierarchical list; the opposite of [cast_hier2dim](cast_hier2dim.qmd). <br />

</li>
<li> [cast_dim2flat](cast_dim2flat.qmd): <br />
casts a dimensional list into a flattened list, but with names that indicate their original dimensional positions. <br />
Mostly useful for printing or summarizing dimensional lists.

</li>
<li> [dropnests](dropnests.qmd): <br />
drop redundant nesting in lists; mostly used for facilitating the above casting functions. <br /> <br />

</li></ul>



### Shared Argument <code>in2out</code>

The [hier2dim](cast_hier2dim.qmd), [cast_hier2dim](cast_hier2dim.qmd), and [cast_dim2hier](cast_dim2hier.qmd) methods
all have the <code>in2out</code> argument. <br />
<br />
<br />
<b><code>in2out = TRUE</code></b> <br />
By default <code>in2out</code> is <code>TRUE</code>. <br />
This means the call <br />
<code>y &lt;- cast_hier2dim(x)</code> <br />
will cast the elements of the deepest valid depth of <code>x</code> to the rows of <code>y</code>,
and elements of the depth above that to the columns of <code>y</code>,
and so on until the surface-level elements of <code>x</code> are cast to the last dimension of <code>y</code>. <br />
<br />
Similarly, the call <br />
<code>x &lt;- cast_dim2hier(y)</code> <br />
will cast the rows of <code>y</code> to the inner most elements of <code>x</code>,
and the columns of <code>y</code> to one depth above that,
and so on until the last dimension of <code>y</code> is cast to the surface-level elements of <code>x</code>. <br />
<br />
Consider the nested list <code>x</code> with a depth of <code>3</code>,
and the recursive array <code>y</code> with 3 dimensions,
where their relationship can described as the following code: <br />
<code>x &lt;- cast_hier2dim(y)</code> <br />
<code>y &lt;- cast_dim2hier(x)</code>. <br />
Then it holds that: <br />
<code>x[[i]][[j]][[k]]</code> corresponds to <code>y[[k, j, i]]</code>, <br />
$\forall$(<code>i</code>, <code>j</code>, <code>k</code>) , provided <code>x[[i]][[j]][[k]]</code> exists. <br />
<br />
<br />
<b><code>in2out = FALSE</code></b> <br />
If <code>in2out = FALSE</code>, the call <br />
<code>y &lt;- cast_hier2dim(x, in2out = FALSE)</code> <br />
will cast the surface-level elements of <code>x</code> to the rows of <code>y</code>,
and elements of the depth below that to the columns of <code>y</code>,
and so on until the elements of the deepest valid depth of <code>x</code> are cast to the last dimension of <code>y</code>. <br />
<br />
Similarly, the call <br />
<code>x &lt;- cast_dim2hier(y, in2out = FALSE)</code> <br />
will cast the rows of <code>y</code> to the surface-level elements of <code>x</code>,
and the columns of <code>y</code> to one depth below that,
and so on until the last dimension of <code>y</code> is cast to the inner most elements of <code>x</code>. <br />
<br />
Consider the nested list <code>x</code> with a depth of <code>3</code>,
and the recursive array <code>y</code> with 3 dimensions,
where their relationship can described with the following code: <br />
<code>x &lt;- cast_hier2dim(y, in2out = FALSE)</code> <br />
<code>y &lt;- cast_dim2hier(x, in2out = FALSE)</code>. <br />
Then it holds that : <br />
<code>x[[i]][[j]][[k]]</code> corresponds to <code>y[[i, j, k]]</code>, <br />
$\forall$(<code>i</code>, <code>j</code>, <code>k</code>) , provided <code>x[[i]][[j]][[k]]</code> exists. <br /> <br />



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE, collapse = TRUE, comment = NA}
library("broadcast")



# evenly nested list ====
x <- list(
  group1 = list(
    class1 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    ),
    class2 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    ),
    class3 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    )
  ),
  group2 = list(
    class1 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    ),
    class2 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    ),
    class3 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    )
  )
)

# the above list is an evenly nested list.



# unevenly nested list ====

# this list is UNEVENLY nested:
x <- list(
  group1 = list(
    class1 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    ),
    class2 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    )
  ),
  group2 = list(
    class1 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    ),
    class2 = list(
      height = rnorm(10, 170),
      sex = sample(c("M", "F", NA), 10, TRUE)
    ),
    class3 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    )
  )
)
# here `x` is UNEVENLY nested because:
# -> not all groups (surface level, or depth = 1) have the same number of classes.
# -> not all classes (depth = 2) have the same number of variables:
#     x$group2$class2 is missing variable "weight".


```
