---
title: bc.b

format:
  html:
    css: /man.css

---
## Broadcasted Boolean Operations {.unnumbered}


### Description

The <code>bc.b()</code> method
performs broadcasted logical (or Boolean) operations on 2 arrays. <br>
<br>
Please note that these operations will treat the input as <code>logical</code>. <br>
Therefore, something like <code>bc.b(1, 2, "==")</code> returns <code>TRUE</code>,
because both <code>1</code> and <code>2</code> are <code>TRUE</code> when treated as <code>logical</code>. <br>
<br>
For regular relational operators, see [bc.rel](bc.rel.qmd). <br> <br>



### Usage

<pre><code class='language-R'>bc.b(x, y, op, ...)

## S4 method for signature 'ANY'
bc.b(x, y, op)
</code></pre>


### Arguments

<table role = "presentation">
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="x">x</code>, <code id="y">y</code></td>
<td>
conformable vectors/arrays of type <code>logical</code>, <code>numeric</code>, or <code>raw</code>. <br>
Note that input with type of <code>double</code> will be coerced to <code>integer</code>.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="op">op</code></td>
<td>
a single string, giving the operator. <br>
Supported Boolean operators:
&amp;, |, xor, nand, nor, ==, !=, &lt;, &gt;, &lt;=, &gt;=. <br>
&quot;nand&quot; is defined here as <code>!(x &amp; y)</code>, and &quot;nor&quot; is defined here as <code>!(x | y)</code>.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="...">...</code></td>
<td>
further arguments passed to or from methods. <br> <br>
</td></tr>
</table>


### Details

<code>bc.b()</code> efficiently casts the input to logical. <br>
Since the input is treated as logical, the following equalities hold for <code>bc.b()</code>:


<ul>
<li> &quot;==&quot; is equivalent to <code>!xor(x, y)</code> (i.e. bi-conditional operation), but faster;

</li>
<li> &quot;!=&quot; is equivalent to <code>xor(x, y)</code>;

</li>
<li> &quot;&lt;&quot; is equivalent to <code>(!x &amp; y)</code> (i.e. only y), but faster;

</li>
<li> &quot;&gt;&quot; is equivalent to <code>(x &amp; !y)</code> (i.e. only x), but faster;

</li>
<li> &quot;&lt;=&quot; is equivalent to <code>(!x &amp; y) | (y == x)</code> (i.e. material implication), but faster;

</li>
<li> &quot;&gt;=&quot; is equivalent to <code>(x &amp; !y) | (y == x)</code> (i.e. converse implication), but faster. <br>

</li></ul>

Note that the <code>&amp;</code> and <code>|</code> operators handle <code>NA</code>s slightly differently than the relational operators. <br> <br>



### Value

Normally: <br>
A logical array/vector as a result of the broadcasted Boolean operation. <br>
<br>
If both <code>x</code> and <code>y</code> are type of raw: <br>
A raw array/vector as a result of the broadcasted Boolean operation,
where <code>01</code> codes for <code>TRUE</code> and <code>00</code> codes for <code>FALSE</code>. <br>
This is convenient as <code>raw</code> requires less memory space than <code>logical</code>. <br> <br>



### See Also

[broadcast_operators](aaa01_broadcast_operators.qmd) <br>



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE, collapse = TRUE, comment = "#>"}
library("broadcast")

x.dim <- c(4:2)
x.len <- prod(x.dim)
x.data <- sample(c(TRUE, FALSE, NA), x.len, TRUE)
x <- array(x.data, x.dim)
y <- array(1:50, c(4,1,1))

bc.b(x, y, "&")
bc.b(x, y, "|")
bc.b(x, y, "xor")
bc.b(x, y, "nand")
bc.b(x, y, "==")
bc.b(x, y, "!=")



```
