---
title: bc.cplx

format:
  html:
    css: /man.css

---
## Broadcasted Complex Numeric Operations {.unnumbered}


### Description

The <code>bc.cplx()</code> method
performs broadcasted complex numeric operations on pairs of arrays. <br>
<br>



### Usage

<pre><code class='language-R'>bc.cplx(x, y, op, ...)

## S4 method for signature 'ANY'
bc.cplx(x, y, op)
</code></pre>


### Arguments

<table role = "presentation">
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="x">x</code>, <code id="y">y</code></td>
<td>
conformable vectors/arrays of type <code>complex</code>.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="op">op</code></td>
<td>
a single string, giving the operator. <br>
Supported arithmetic operators: +, -, *, /. <br>
Supported relational operators: ==, !=.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="...">...</code></td>
<td>
further arguments passed to or from methods. <br> <br>
</td></tr>
</table>


### Details

For the <code>*</code> and <code>/</code> operators, <code>bc.cplx()</code> uses more strict <code>NA</code> checks than base 'R': <br>
If for an iteration,
<code>re(x)</code>, <code>im(x)</code>, <code>re(y)</code>, and/or <code>im(y)</code> contains <code>NA</code>,
than the result for that iteration is necessarily <code>NA_complex_</code>.



### Value

For arithmetic operators: <br>
A complex array as a result of the broadcasted arithmetic operation. <br>
<br>
For relational operators: <br>
A logical array as a result of the broadcasted relational comparison. <br>
<br>



### See Also

[broadcast_operators](aaa01_broadcast_operators.qmd) <br>



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE, collapse = TRUE, comment = "#>"}
library("broadcast")

x.dim <- c(4:2)
x.len <- prod(x.dim)
gen <- function() sample(c(rnorm(20), NA, NaN, Inf, -Inf))
x <- array(gen() + gen() * -1i, x.dim)
y <- array(gen() + gen() * -1i, c(4,1,1))

bc.cplx(x, y, "==")
bc.cplx(x, y, "!=")

bc.cplx(x, y, "+")

bc.cplx(array(gen() + gen() * -1i), array(gen() + gen() * -1i), "==")
bc.cplx(array(gen() + gen() * -1i), array(gen() + gen() * -1i), "!=")

x <- array(gen() + gen() * -1i)
y <- array(gen() + gen() * -1i)
bcr(x) <- bcr(y) <- TRUE
out <- x * y
bind_array(list(x = x, y = y, `x*y` = x*y, out = out), 2L)


```
