---
title: bc.raw
---
## Broadcasted Operations that Take Raw Arrays and Return Raw Arrays {.unnumbered}


### Description

The <code>bc.raw()</code> function
performs broadcasted operations
on arrays of type <code>raw</code>, and the return type is <b>always</b> <code>raw</code>. <br />
<br />
For bit-wise operations, use [bc.bit](bc.bit.qmd). <br />
For regular logical operations, use [bc.b](bc.b.qmd). <br />
For relational operations with logical (<code>TRUE</code>/<code>FALSE</code>/<code>NA</code>) results, use [bc.rel](bc.rel.qmd). <br />
<br />



### Usage

<pre><code class='language-R'>bc.raw(x, y, op, ...)

## S4 method for signature 'ANY'
bc.raw(x, y, op)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="x">x</code>, <code id="y">y</code></td>
<td>
conformable raw vectors or arrays.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="op">op</code></td>
<td>
a single string, giving the operator. <br />
Supported operators: ==, !=, &lt;, &gt;, &lt;=, &gt;=, &amp;, |, xor, nand, both, pmin, pmax, diff. <br />
The logical and relational operators work the same as in [bc.b](bc.b.qmd) and [bc.rel](bc.rel.qmd),
respectively, but with the following difference: <br />
a <code>TRUE</code> result is replaced with <code>01</code>,
and a <code>FALSE</code> result is replaced with <code>00</code>. <br />
The &quot;both&quot; operator checks if both <code>x</code> and <code>y</code> are
<code style="white-space: pre;">&gt;= 01</code> (i.e. &quot;true&quot;) or both are <code>00</code> (i.e. &quot;false&quot;). <br />
The &quot;diff&quot; operator performs the byte equivalent of <code>abs(x - y)</code>.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="...">...</code></td>
<td>
further arguments passed to or from methods. <br /> <br />
</td></tr>
</table>


### Details

Each element of a <code>raw</code> vector only takes 1 byte (= 8 bits),
making it useful in situations where minimizing memory usage as much as possible
is absolutely vital. <br /> <br />



### Value

<code>bc.raw()</code> <b>always</b> returns an array of type <code>raw</code>. <br />
For the logical and relational operators, <code>01</code> codes for <code>TRUE</code>, and <code>00</code> codes for <code>FALSE</code>. <br />
<br />



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE, collapse = TRUE, comment = NA}
library("broadcast")


x <- array(
  sample(as.raw(1:100)), c(5, 3, 2)
)
y <- array(
  sample(as.raw(1:100)), c(5, 1, 1)
)

cond <- bc.raw(x, y, "!=")
print(cond)

bc_ifelse(cond, yes = x, no = y)




```
