---
title: bc.str

format:
  html:
    css: /man.css

---
## Broadcasted String Operations {.unnumbered}


### Description

The <code>bc.str()</code> method
performs broadcasted string operations on pairs of arrays. <br> <br>



### Usage

<pre><code class='language-R'>bc.str(x, y, op, ...)

## S4 method for signature 'ANY'
bc.str(x, y, op)
</code></pre>


### Arguments

<table role = "presentation">
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="x">x</code>, <code id="y">y</code></td>
<td>
conformable vectors/arrays of type <code>character</code>.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="op">op</code></td>
<td>
a single string, giving the operator. <br>
Supported concatenation operators: +. <br>
Supported relational operators: ==, !=. <br>
Supported distance operators: levenshtein, lcss. <br>
&quot;lcss&quot; stands for Longest Common Sub-String.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="...">...</code></td>
<td>
further arguments passed to or from methods. <br> <br>
</td></tr>
</table>


### Value

For concatenation operation: <br>
A character array as a result of the broadcasted concatenation operation. <br>
<br>
For relational operation: <br>
A logical array as a result of the broadcasted relational comparison. <br>
<br>
For distance operation: <br>
An integer array as a result of the broadcasted distance measurement. <br>
<br>



### References

The 'C++' code for the Levenshtein edit string distance is based on the code found in
<a href="https://rosettacode.org/wiki/Levenshtein_distance#C++">https://rosettacode.org/wiki/Levenshtein_distance#C++</a>



### See Also

[broadcast_operators](aaa01_broadcast_operators.qmd) <br>



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE, collapse = TRUE, comment = "#>"}
library("broadcast")


# string concatenation:
x <- array(letters, c(10, 2, 1))
y <- array(letters, c(10,1,1))
bc.str(x, y, "+")


# string (in)equality:
bc.str(array(letters), array(letters), "==")
bc.str(array(letters), array(letters), "!=")


# string distances:
x <- setNames(month.name, month.name) |> vector2array(1L)
y <- setNames(month.abb, month.abb) |> vector2array(2L)
bc.str(x, y, "levenshtein") # levenshtein
bc.str(x, y, "lcss") # longest common sub-string


```
