---
title: bc_ifelse
---
## Broadcasted Ifelse {.unnumbered}


### Description

The <code>bc_ifelse()</code> function
performs a broadcasted form of <code>ifelse()</code>. <br />



### Usage

<pre><code class='language-R'>bc_ifelse(test, yes, no, ...)

## S4 method for signature 'ANY'
bc_ifelse(test, yes, no)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="test">test</code></td>
<td>
a vector or array,
with the type <code>logical</code>, <code>integer</code>, or <code>raw</code>,
and a length equal to <code>prod(bc_dim(yes, no))</code>. <br />
If <code>yes</code> / <code>no</code> are of type <code>raw</code>, <code>test</code> is not allowed to contain any <code>NA</code>s.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="yes">yes</code>, <code id="no">no</code></td>
<td>
conformable arrays of the same type. <br />
All atomic types are supported. <br />
Recursive arrays of type list are also supported.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="...">...</code></td>
<td>
further arguments passed to or from methods. <br /> <br />
</td></tr>
</table>


### Value

The output, here referred to as <code>out</code>,
will be an array of the same type as <code>yes</code> and <code>no</code>. <br />
If <code>test</code> has the same dimensions as <code>bc_dim(yes, no)</code>,
then <code>out</code> will also have the same dimnames as <code>test</code>. <br />
If <code>test</code> is a [broadcaster](broadcaster.qmd), then <code>out</code> will also be a [broadcaster](broadcaster.qmd). <br />
<br />
After broadcasting <code>yes</code> against <code>no</code>,
given any element index <code>i</code>,
the following will hold for the output:


<ul>
<li> when <code>test[i] == TRUE</code>, <code>out[i]</code> is <code>yes[i]</code>;

</li>
<li> when <code>test[i] == FALSE</code>, <code>out[i]</code> is <code>no[i]</code>;

</li>
<li> when <code>test[i]</code> is <code>NA</code>,
<code>out[i]</code> is <code>NA</code> when <code>yes</code> and <code>no</code> are atomic,
and <code>out[i]</code> is <code>list(NULL)</code> when <code>yes</code> and <code>no</code> are recursive. <br /> <br />

</li></ul>



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE, collapse = TRUE, comment = NA}
library("broadcast")


x.dim <- c(5, 3, 2)
x.len <- prod(x.dim)

x <- array(sample(1:100), x.dim)
y <- array(sample(1:100), c(5, 1, 1))

cond <- bc.i(x, y, ">")

bc_ifelse(cond, yes = x^2, no = -y)


```
