---
title: bcapply
---
## Apply Function to Pair of Arrays with Broadcasting {.unnumbered}


### Description

The <code>bcapply()</code> method
applies a function to 2 arrays element-wise with broadcasting. <br />



### Usage

<pre><code class='language-R'>bcapply(x, y, f, ...)

## S4 method for signature 'ANY'
bcapply(x, y, f, v = NULL)
</code></pre>


### Arguments

<table role = "presentation">
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="x">x</code>, <code id="y">y</code></td>
<td>
conformable atomic or recursive vectors/arrays.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="f">f</code></td>
<td>
a function that takes in exactly <b>2</b> arguments,
and <b>returns</b> a result
that can be stored in a single element of a recursive or atomic array.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="...">...</code></td>
<td>
further arguments passed to or from methods. <br /> <br />
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="v">v</code></td>
<td>
either <code>NULL</code>, or single string, giving the scalar type for a single iteration. <br />
If <code>NULL</code> (default) or <code>"list"</code>, the result will be a recursive array. <br />
If it is certain that, for every iteration,
<code>f()</code> always results in a <b>single atomic scalar</b>,
the user can specify the type in <code>v</code> to pre-allocate the result. <br />
Pre-allocating the results leads to slightly faster and more memory efficient code. <br />
NOTE: Incorrectly specifying <code>v</code> leads to undefined behaviour; <br />
when unsure, leave <code>v</code> at its default value.
</td></tr>
</table>


### Value

An atomic or recursive array with dimensions <code>bc_dim(x, y)</code>. <br />
Preserves some of the attributes of <code>x</code> and <code>y</code> similar to broadcasted infix operators,
as explained in [broadcast_operators](aaa01_broadcast_operators.qmd). <br /> <br />



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE, collapse = TRUE, comment = NA}
library("broadcast")



# check for each element in one recursive array if values are present in another:
mylist <- list(
  as.raw(0:255),
  sample(c(TRUE, FALSE, NA), 100, TRUE),
  0:255,
  rnorm(10),
  rnorm(10) + rnorm(10) * -1i,
  sample(month.abb)
)
mylist <- c(mylist, list(mylist))
x <- array(sample(mylist, 50, TRUE), c(5, 5, 2))
y <- array(sample(mylist, 50, TRUE), c(5, 5, 2))

bcapply(x, y, `%in%`) # returns a dimensional list / recursive array

bcapply(x, y, \(x, y) any(x %in% y), v = "logical") # returns logical array

bcapply(x, y, \(x, y) all(x %in% y), v = "logical") # returns logical array



# calculate quartiles for each list item, and return numeric array of quartiles:
x <- list(
  a = 1:10,
  beta = exp(-3:3),
  logic = c(TRUE,FALSE,FALSE,TRUE)
)
print(x)
quantiles <- array(c(1:3/4), c(1, 3))
colnames(quantiles) <- paste0("q = ", quantiles)
print(quantiles)

out <- bcapply(x, quantiles, \(x, y) quantile(x, probs = y), v = "double")
print(out)
typeof(out)


```
