---
title: bind
---
## Dimensional Binding of Objects {.unnumbered}


### Description

The <code>bind_</code>implementations provide dimensional binding functionalities. <br />
<br />
The following implementations are available:


<ul>
<li> <code>bind_mat()</code> binds dimensionless (atomic/recursive) vectors and (atomic/recursive) matrices row- or column-wise. <br />
Returns a matrix. <br />
Allows for linear/vector recycling.

</li>
<li> <code>bind_array()</code> binds (atomic/recursive) arrays and (atomic/recursive) matrices. <br />
Returns an array. <br />
Allows for broadcasting.

</li>
<li> <code>bind_dt()</code> binds data.tables and other data.frame-like objects. <br />
Returns a <code>data.table</code>. <br />
This function is only available if the 'data.table' package is installed. <br />
The <code>bind_dt()</code> function is faster than <code>do.call(cbind, ...)</code> or <code>do.call(rbind, ...)</code> for regular <code>data.frame</code> objects. <br />

</li></ul>



### Usage

<pre><code class='language-R'>bind_mat(input, along, name_deparse = TRUE, comnames_from = 1L)

bind_array(
  input,
  along,
  rev = FALSE,
  ndim2bc = 1L,
  name_along = TRUE,
  comnames_from = 1L
)

bind_dt(input, along, ...)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="input">input</code></td>
<td>
a list of only the appropriate objects. <br />
If <code>input</code> is named,
its names will be used for the names of dimension <code>along</code> of the output,
as far as possible.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="along">along</code></td>
<td>
a single integer,
indicating the dimension along which to bind the dimensions. <br />
I.e. use <code>along = 1</code> for row-binding, <code>along = 2</code> for column-binding, etc. <br />
For arrays, additional flexibility is available:


<ul>
<li> Specifying <code>along = 0</code> will bind the arrays on a new dimension before the first,
making <code>along</code> the new first dimension.

</li>
<li> Specifying <code>along = N + 1</code>, with <code style="white-space: pre;">N = </code>max<code>(</code>[lst.ndim](properties.qmd)<code style="white-space: pre;">(input))</code>,
will create an additional dimension (<code>N + 1</code>) and bind the arrays along that new dimension.

</li></ul>
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="name_deparse">name_deparse</code></td>
<td>
Boolean, for <code>bind_mat()</code>. <br />
Indicates if dimension <code>along</code> should be named. <br />
Uses the naming method from rbind/cbind itself.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="comnames_from">comnames_from</code></td>
<td>
either integer scalar or <code>NULL</code>,
for <code>bind_mat()</code> and  <code>bind_array()</code>. <br />
Indicates which object in <code>input</code> should be used for naming the shared dimension. <br />
If <code>NULL</code>, no communal names will be given. <br />
For example: <br />
When binding columns of matrices, the matrices will share the same rownames. <br />
Using <code>comnames_from = 10</code> will then result in <code>bind_array()</code> using
<code>rownames(input[[10]])</code> for the rownames of the output.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="rev">rev</code></td>
<td>
Boolean, for <code>bind_array()</code> only. <br />
Indicates if <code>along</code> should be reversed, counting backwards. <br />
If <code>FALSE</code> (default), <code>along</code> works like normally; if <code>TRUE</code>, <code>along</code> is reversed. <br />
I.e. <code style="white-space: pre;">along = 0, rev = TRUE</code> is equivalent to <code style="white-space: pre;">along = N+1, rev = FALSE</code>; <br />
and <code style="white-space: pre;">along = N+1, rev = TRUE</code> is equivalent to <code style="white-space: pre;">along = 0, rev = FALSE</code>; <br />
with <code style="white-space: pre;">N = </code>max<code>(</code>[lst.ndim](properties.qmd)<code style="white-space: pre;">(input))</code>.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="ndim2bc">ndim2bc</code></td>
<td>
non-negative integer, for <code>bind_array</code> only. <br />
Specify here the maximum number of dimensions that are allowed to be broadcasted when binding arrays. <br />
If <code>ndim2bc = 0L</code>, <b>no</b> broadcasting will be allowed at all.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="name_along">name_along</code></td>
<td>
Boolean, for <code>bind_array()</code>. <br />
Indicates if dimension <code>along</code> should be named. <br />
The examples section illustrates the naming behaviour.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="...">...</code></td>
<td>
arguments to be passed to <code>data.table::rbindlist()</code>. <br /> <br />
</td></tr>
</table>


### Details

For in-depth information about the binding implentations in the 'broadcast' package,
please refer to broadcast_bind. <br />
<br />



### Value

The bound object.



### References

Plate T, Heiberger R (2016). <em>abind: Combine Multidimensional Arrays</em>. R package version 1.4-5, <a href="https://CRAN.R-project.org/package=abind">https://CRAN.R-project.org/package=abind</a>.



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE, collapse = TRUE, comment = NA}
library("broadcast")


# bind_array ====

# here, atomic and recursive arrays are mixed,
# resulting in recursive arrays

# creating the arrays
x <- c(
  lapply(1:3, \(x)sample(c(TRUE, FALSE, NA))),
  lapply(1:3, \(x)sample(1:10)),
  lapply(1:3, \(x)rnorm(10)),
  lapply(1:3, \(x)sample(letters))
)
x <- matrix(x, 4, 3, byrow = TRUE)
dimnames(x) <- list(letters[1:4], LETTERS[1:3])
print(x)

y <- matrix(1:12, 4, 3)
print(y)

# binding the arrays
input <- list(x = x, y = y)
bind_array(input, along = 0L) # binds on new dimension before first
bind_array(input, along = 1L) # binds on first dimension (i.e. rows)
bind_array(input, along = 2L)
bind_array(input, along = 3L) # bind on new dimension after last

bind_array(input, along = 0L, TRUE) # binds on new dimension after last
bind_array(input, along = 1L, TRUE) # binds on last dimension (i.e. columns)
bind_array(input, along = 2L, TRUE)
bind_array(input, along = 3L, TRUE) # bind on new dimension before first


# binding, with empty arrays
emptyarray <- array(numeric(0L), c(0L, 3L))
dimnames(emptyarray) <- list(NULL, paste("empty", 1:3))
print(emptyarray)
input <- list(x = x, y = emptyarray)
bind_array(input, along = 1L, comnames_from = 2L) # row-bind


# Illustrating `name_along`

x <- array(1:20, c(5, 3), list(NULL, LETTERS[1:3]))
y <- array(-1:-20, c(5, 3))
z <- array(-1:-20, c(5, 3))

bind_array(list(a = x, b = y, z), 2L)
bind_array(list(x, y, z), 2L)
bind_array(list(a = unname(x), b = y, c = z), 2L)
bind_array(list(x, a = y, b = z), 2L)
input <- list(x, y, z)
names(input) <- c("", NA, "")
bind_array(input, 2L)


################################################################################

# bind_mat ====

# here, atomic and recursive matrices are mixed,
# resulting in a recursive matrix

x <- c(
  lapply(1:3, \(x)sample(c(TRUE, FALSE, NA))),
  lapply(1:3, \(x)sample(1:10)),
  lapply(1:3, \(x)rnorm(10)),
  lapply(1:3, \(x)sample(letters))
)
x <- matrix(x, 4, 3, byrow = TRUE)
dimnames(x) <- list(letters[1:4], LETTERS[1:3])
print(x)

y <- matrix(1:12, 4, 3)
print(y)

bind_mat(list(x = x, y = y), 2L)



################################################################################

# bind_dt ====
if(require(data.table)) {
  x <- data.frame(a = 1:12, b = month.abb) # data.frame
  y <- data.table::data.table(a = 1:12, b = month.abb) # data.table
  
  bind_dt(list(x = x, y = y), 2L) # column bind
  
  bind_dt(list(x = x, y = y), 1L) # row bind
  
}




```
