---
title: broadcaster

format:
  html:
    css: /man.css

---
## Check or Set if an Array is a Broadcaster {.unnumbered}


### Description

<code>broadcaster()</code> checks if an array or vector is marked as a &quot;broadcaster&quot;. <br>
<code>bcr()</code> is a short-hand alias for <code>broadcaster()</code>. <br>
<br>
<code style="white-space: pre;">broadcaster()&lt;-</code> (or <code style="white-space: pre;">bcr()&lt;-</code>) marks or un-marks the object as a &quot;broadcaster&quot;. <br>
<br>
<code>mbroadcasters()</code> marks or un-marks multiple objects in an environment as broadcaster. <br>
<br>
The <code>broadcaster</code> class attribute exists purely to overload the
arithmetic, Boolean, bit-wise, and relational infix operators,
to support broadcasting. <br>
This makes mathematical expressions with multiple variables,
where precedence may be important,
far more convenient. <br>
Like in the following calculation: <br>
<code>x / (y + z)</code> <br>
<br>
See [broadcast_operators](aaa01_broadcast_operators.qmd) for more information. <br>



### Usage

<pre><code class='language-R'>broadcaster(x)

broadcaster(x) &lt;- value

mbroadcasters(nms, value, env = NULL)

bcr(x)

bcr(x) &lt;- value
</code></pre>


### Arguments

<table role = "presentation">
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="x">x</code></td>
<td>
object to check or mark. <br>
Only S3 vectors and arrays are supported, and only up to 16 dimensions.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="value">value</code></td>
<td>
set to <code>TRUE</code> to make an array a broadcaster,
or <code>FALSE</code> to remove the broadcaster class attribute from an array.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="nms">nms</code></td>
<td>
a character vector of variable names.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="env">env</code></td>
<td>
the environment where to look for the variable names specified in <code>nms</code>. <br>
If <code>NULL</code>, the environment from which the function was called is used. <br>
</td></tr>
</table>


### Value

For <code>broadcaster()</code>: <br>
<code>TRUE</code> if an array or vector is a broadcaster, or <code>FALSE</code> if it is not. <br>
<br>
For <code style="white-space: pre;">broadcaster()&lt;-</code>: <br>
Returns nothing,
but marks (if right hand side is <code>TRUE</code>)
or un-marks (if right hand side is <code>FALSE</code>)
the object as a &quot;broadcaster&quot;. <br>
<br>
For <code>mbroadcasters()</code>: <br>
Returns nothing,
but marks (if right hand side is <code>TRUE</code>)
or un-marks (if right hand side is <code>FALSE</code>)
the objects as broadcasters. <br>
If <code>value = TRUE</code>,
objects that cannot become a broadcaster or are already a broadcaster
will be ignored. <br>
If <code>value = FALSE</code>,
objects that are not broadcasters (according to <code>broadcaster()</code>)
will be ignored. <br>
<br>



### Note

The 'broadcaster' class will make arithmetic and relational operators operate with broadcasting. <br>
Functions that rely on non-broadcasted functionality of these operators
will produce unexpected results. <br>
Thus functions like <code>pmin()</code> and <code>pmax()</code>,
and some functions from the 'tinyplot' package,
are <b>not</b> compatible with 'broadcaster' vectors/arrays. <br>
Please ensure an object is not a 'broadcaster' before applying these functions on it. <br>
<br>



### See Also

[broadcast_operators](aaa01_broadcast_operators.qmd) <br>



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE, collapse = TRUE, comment = "#>"}
library("broadcast")


# maths ====

x <- 1:10
y <- 1:10
dim(x) <- c(10, 1)
dim(y) <- c(1, 10)
broadcaster(x) <- TRUE
broadcaster(y) <- TRUE



x + y / x
(x + y) / x

(x + y) * x


# relational operators ====
x <- 1:10
y <- array(1:10, c(1, 10))
broadcaster(x) <- TRUE
broadcaster(y) <- TRUE

x == y
x != y
x < y
x > y
x <= y
x >= y




# maths ====

x <- sample(1:10)
y <- sample(1:10)
dim(x) <- c(10, 1)
dim(y) <- c(1, 10)
mbroadcasters(c("x", "y"), TRUE)



x + y / x
(x + y) / x

(x + y) * x


# relational operators ====
x <- 1:10
y <- array(1:10, c(1, 10))
mbroadcasters(c("x", "y"), TRUE)

x == y
x != y
x < y
x > y
x <= y
x >= y




```
