---
title: dropnests
---
## Drop Redundant List Nesting {.unnumbered}


### Description

<code>dropnests()</code> drops redundant nesting of a list. <br />
It is the hierarchical equivalent to the dimensional drop function. <br />
<br />
<code>depth_range()</code> gives the minimum and maximum depth of a list. <br />



### Usage

<pre><code class='language-R'>dropnests(x, ...)

depth_range(x, ...)

## Default S3 method:
dropnests(x, maxdepth = 32L, recurse_classed = FALSE, ...)

## Default S3 method:
depth_range(x, maxdepth = 32L, recurse_classed = FALSE, ...)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="x">x</code></td>
<td>
a list
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="...">...</code></td>
<td>
further arguments passed to or from methods. <br /> <br />
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="maxdepth">maxdepth</code></td>
<td>
a single, positive integer,
giving the maximum depth to recurse into the list. <br />
The surface-level elements of a list is depth 1. <br />
<code>dropnests(x, maxdepth = 1)</code> will return <code>x</code> unchanged.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="recurse_classed">recurse_classed</code></td>
<td>
<code>TRUE</code> or <code>FALSE</code>,
indicating if the function should also recurse through classed lists within <code>x</code>,
like data.frames.
</td></tr>
</table>


### Value

For <code>dropnests()</code>: <br />
A list without redundant nesting. <br />
Attributes are preserved. <br />
<br />
For <code>depth_range()</code>: <br />
An integer vector of length 2,
where the first element gives the minimum depth found,
and the second element gives the maximum depth found. <br /> <br />



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE, collapse = TRUE, comment = NA}
library("broadcast")


x <- list(
  list(list(list(list(1:10)))),
  list(1:10)
)
print(x)

depth_range(x)
dropnests(x)


# recurse_classed demonstration ====
x <- list(
  list(list(list(list(1:10)))),
  data.frame(month.abb, month.name),
  data.frame(month.abb)
)

depth_range(x)
dropnests(x) # by default, recurse_classed = FALSE

depth_range(x, recurse_classed = TRUE)
dropnests(x, recurse_classed = TRUE)


# maxdepth demonstration ====
x <- list(
  list(list(list(list(1:10)))),
  list(1:10)
)
print(x)

depth_range(x)
dropnests(x) # by default, maxdepth = 32

depth_range(x, maxdepth = 3L)
dropnests(x, maxdepth = 3L)

depth_range(x, maxdepth = 1L)
dropnests(x, maxdepth = 1L) # returns `x` unchanged



```
