---
title: hier2dim
---
## Helper Functions For cast_hier2dim {.unnumbered}


### Description

<code>hier2dim()</code> takes a hierarchical/nested list,
and predicts what dimensions the list would have,
if casted by the [cast_hier2dim](cast_hier2dim.qmd) function. <br />
<br />
<code>hiernames2dimnames()</code> takes a hierarchical/nested list,
and intelligently tries to compose dimnames for the result of [cast_hier2dim](cast_hier2dim.qmd). <br />
<br />



### Usage

<pre><code class='language-R'>hier2dim(x, ...)

hiernames2dimnames(x, ...)

## Default S3 method:
hier2dim(x, in2out = TRUE, maxdepth = 16L, recurse_all = FALSE, ...)

## Default S3 method:
hiernames2dimnames(
  x,
  in2out = TRUE,
  maxdepth = 16L,
  recurse_all = FALSE,
  direction = 1,
  ...
)
</code></pre>


### Arguments

<table role = "presentation">
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="x">x</code></td>
<td>
a nested list. <br />
If <code>x</code> has redundant nesting,
it is advisable (though not necessary) to reduce the redundant nesting using [dropnests](dropnests.qmd).
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="...">...</code></td>
<td>
further arguments passed to or from methods. <br /> <br />
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="in2out">in2out</code>, <code id="recurse_all">recurse_all</code></td>
<td>
see [broadcast_casting](aaa02_broadcast_casting.qmd).
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="maxdepth">maxdepth</code></td>
<td>
a single, positive integer,
giving the maximum depth to recurse into the list. <br />
The surface-level elements of a list is depth 1. <br />
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="direction">direction</code></td>
<td>
A single number, giving the direction in which to search for names. <br />
Must be either <code>1</code> (to search from start to end) or <code>-1</code> (to search from end to start). <br />
If set to <code>0</code>, the result will simply be <code>NULL</code>.
</td></tr>
</table>


### Value

For <code>hier2dim()</code>: <br />
An integer vector,
giving the dimensions <code>x</code> would have,
if casted by <code>cast_hier2dim()</code>. <br />
The names of the output indicates if padding is required (name &quot;padding&quot;),
or no padding is required (no name) for that dimension; <br />
Padding will be required if not all list-elements at a certain depth have the same length. <br />
<br />
For <code>hiernames2dimnames()</code>: <br />
A list of <code>dimnames</code>; these can be assigned to the <code>dimnames</code> of the result of [cast_hier2dim](cast_hier2dim.qmd). <br />
<br />



### See Also

[broadcast_casting](aaa02_broadcast_casting.qmd), [cast_hier2dim](cast_hier2dim.qmd) <br />



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE, collapse = TRUE, comment = NA}
library("broadcast")



# Example 1: Basics ====
x <- list(
  group1 = list(
    class1 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    ),
    class2 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    )
  ),
  group2 = list(
    class1 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    ),
    class2 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    )
  )
)

# predict what dimensions `x` would have if casted as dimensional:
hier2dim(x)

x2 <- cast_hier2dim(x) # cast as dimensional

# since the original list uses the same names for all elements within the same depth,
# dimnames can be set easily:
dimnames(x2) <- hiernames2dimnames(x)

print(x2)


################################################################################


# Example 2: Cast from outside to inside ====
x <- list(
  group1 = list(
    class1 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    ),
    class2 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    )
  ),
  group2 = list(
    class1 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    ),
    class2 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    )
  )
)

# by default, `in2out = TRUE`;
# for this example, `in2out = FALSE` is used

# predict what dimensions `x` would have if casted as dimensional:
hier2dim(x, in2out = FALSE)

x2 <- cast_hier2dim(x, in2out = FALSE) # cast as dimensional

# since the original list uses the same names for all elements within the same depth,
# dimnames can be set easily:
# because in2out = FALSE, go from the shallow names to the deeper names:
dimnames(x2) <- hiernames2dimnames(x, in2out = FALSE)

print(x2)


################################################################################


# Example 3: padding ====

# For Example 3, take the same list as before, but remove x$group1$class2:

x <- list(
  group1 = list(
    class1 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    )
  ),
  group2 = list(
    class1 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    ),
    class2 = list(
      height = rnorm(10, 170),
      weight = rnorm(10, 80),
      sex = sample(c("M", "F", NA), 10, TRUE)
    )
  )
)


hier2dim(x) # as indicated here, dimension 2 (i.e. columns) will have padding

# casting this to a dimensional list will resulting in padding with `NULL`:
x2 <- cast_hier2dim(x)
print(x2)
# The `NULL` values are added for padding.
# This is because all slices of the same dimension need to have the same number of elements.  
# For example, all rows need to have the same number of columns.

# one can also use custom padding:
x2 <- cast_hier2dim(x, padding = list(~ "this is padding"))
print(x2)

dimnames(x2) <- hiernames2dimnames(x)

print(x2)


# we can also use in2out = FALSE:
x2 <- cast_hier2dim(x, in2out = FALSE, padding = list(~ "this is padding"))
dimnames(x2) <- hiernames2dimnames(x, in2out = FALSE)
print(x2)




```
