---
title: vector2array

format:
  html:
    css: /man.css

---
## Turn Vector to Array and Vice-Versa {.unnumbered}


### Description

<code>vector2array()</code> turns a vector into an array,
with a specific vector orientation,
and turning the names into dimnames, and keeping (or forcing) [broadcaster](broadcaster.qmd) attribute. <br>
<br>
<code>undim()</code> returns a copy of an object, but with its dimensions removed,
but still trying to keep the names if possible
(it somewhat is like the dimensional version of <code>unlist()</code>). <br>
<code>undim()</code> will also keep (or force) the [broadcaster](broadcaster.qmd) attribute
<br>
<code>array2vector()</code> is an alias for <code>undim()</code>. <br> <br>



### Usage

<pre><code class='language-R'>vector2array(x, orient, ndim = orient, broadcaster = NULL)

undim(x, broadcaster = NULL)

array2vector(x, broadcaster = NULL)
</code></pre>


### Arguments

<table role = "presentation">
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="x">x</code></td>
<td>
an vector (for <code>vector2array()</code> or an array (for <code>undim()</code>/<code>array2vector()</code>). <br>
All atomic types, and the recursive type <code>list</code>, are supported.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="orient">orient</code></td>
<td>
a positive integer scalar, giving the orientation of the vector. <br>
In other words: give here which dimension should have size <code>length(x)</code> - all other dimensions will have size <code>1</code>.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="ndim">ndim</code></td>
<td>
the number of dimensions in total. <br>
It must be the case that <code>ndim &gt;= orient</code>, and <code>ndim &lt;= 16L</code>.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="broadcaster">broadcaster</code></td>
<td>
<code>TRUE</code> or <code>FALSE</code>, indicating if the result should be a broadcaster. <br>
If <code>NULL</code>, <code>broadcaster(x)</code> will be used. <br>
</td></tr>
</table>


### Value

For <code>vector2array()</code>: <br>
If <code>x</code> is already an array, <code>x</code> is returned unchanged. <br>
Otherwise, given <code>out <- vector2array(x, orient, ndim)</code>,
<code>out</code> will be an array with the following properties:


<ul>
<li> <code>ndim(out) == ndim</code>;

</li>
<li> <code>dim(out)[orient] == length(x)</code>, and all other dimensions will be <code>1</code>;

</li>
<li> <code>dimnames(out)[[orient]] == names(x)</code>, and all other <code>dimnames</code> will be <code>NULL</code>. <br> <br>

</li></ul>

For <code>undim()</code>: <br>
If <code>x</code> is not an array, <code>x</code> is returned unchanged. <br>
Otherwise, a copy of the original object, but without dimensions,
but keeping names and [broadcaster](broadcaster.qmd) attribute as far as possible. <br> <br>



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE, collapse = TRUE, comment = "#>"}
library("broadcast")


x <- setNames(1:27, c(letters, NA))
print(x)
y <- vector2array(x, 1L, 3L)
print(y)

undim(y)


```
