project:
  type: website


website:
  title: "R-package: broadcast"
  favicon: man/figures/broadcast.png
  navbar:
    background: "gray"
    search: true
    pinned: true
    left:
      - text: Guides and Vignettes
        href: vignettes/a_readme.qmd
      - text: Reference Manual
        href: man/aaa00_broadcast_help.qmd
      - text: About
        href: about/LICENSE.qmd

  sidebar:
    - title: Guides and Vignettes
      style: docked
      collapse-level: 1
      contents:
      - auto: vignettes/*
    
    - title: Reference Manual
      contents:
      - text: broadcast
        href: man/aaa00_broadcast_help.qmd
      - man/bc.b.qmd
      - man/bc.i.qmd
      - man/bc.d.qmd
      - man/bc.cplx.qmd
      - man/bc.str.qmd
      - man/bc.list.qmd
      - man/bc_ifelse.qmd
      - man/bcapply.qmd
      - man/bind.qmd
      - text: binding implementation details
        href: man/aaa01_broadcast_bind.qmd
      - man/array_replicate.qmd
      - man/properties.qmd
    
    - title: About
      contents: about/*

format:
  html:
    fontsize: 1.2em
    toc: true
    theme: [pandoc, light.css]

