project:
  type: website


website:
  search:
    location: navbar
    type: textbox
  title: "R-package: broadcast"
  favicon: man/figures/broadcast.png
  navbar:
    background: "#F5F5F5"
    pinned: true
    left:
      - text: Guides and Vignettes
        href: vignettes/a_readme.qmd
      - text: Reference Manual
        href: man/aaa00_broadcast_help.qmd
      - text: About
        href: about/Acknowledgements.qmd

  sidebar:
    - title: Guides and Vignettes
      style: docked
      collapse-level: 1
      contents:
      - text: Guides and Vignettes
      - auto: vignettes/*
    
    - title: Reference Manual
      contents:
      - text: Reference Manual
      - text: broadcast help
        href: man/aaa00_broadcast_help.qmd
      - man/bc.b.qmd
      - man/bc.i.qmd
      - man/bc.d.qmd
      - man/bc.cplx.qmd
      - man/bc.str.qmd
      - man/bc.list.qmd
      - man/bc_ifelse.qmd
      - man/bcapply.qmd
      - man/bind.qmd
      - text: binding implementation details
        href: man/aaa01_broadcast_bind.qmd
      - man/acast.qmd
      - man/typecast.qmd
      - man/rep_dim.qmd
      - man/properties.qmd
    
    - title: About
      contents:
      - text: About
      - auto: about/*

format:
  html:
    fontsize: 1.2em
    fontcolor: "#18161B"
    mainfont: Tahoma
    toc: true
    theme: [pandoc, light.css]

