project:
  type: website


website:
  title: "broadcast"
  favicon: man/figures/broadcast.png
  navbar:
    background: "#FCF5E5"
    search: true
    pinned: true
    left:
      - text: Guides and Vignettes
        href: vignettes/a_readme.qmd
      - text: Reference Manual
        href: man/aaa00_broadcast_help.qmd
      - text: About
        href: about/LICENSE.qmd

  sidebar:
    - title: Guides and Vignettes
      style: docked
      collapse-level: 1
      contents:
      - auto: vignettes/*
    
    - title: Reference Manual
      contents:
      - text: broadcast
        href: man/aaa00_broadcast_help.qmd
      - section: outer computations
        contents:
        - man/outer/bc.b.qmd
        - man/outer/bc.i.qmd
        - man/outer/bc.d.qmd
        - man/outer/bc.cplx.qmd
        - man/outer/bc.str.qmd
        - man/outer/bc.list.qmd
      - section: generic fuctions
        contents: man/generic/*
      - section: binding implementations
        contents: man/bind/*
      - section: other functions
        contents: man/other/*
    
    - title: About
      contents: about/*

format:
  html:
    fontsize: 1.2em
    toc: true
    theme: [pandoc, light.css]

