project:
  type: website

website:
  title: "broadcast"
  navbar:
    left:
      - text: Guides
        href: vignettes/a_installation.qmd
      - text: Reference
        href: man/aaa00_broadcast_help.qmd
      - text: About
        href: about/LICENSE.qmd

  sidebar:
    - title: Guides
      contents: vignettes/*
    
    - title: References
      contents: man/*
    
    - title: Abput
      contents: about/*

format:
  html:
    theme: cosmo
    toc: true


