// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/broadcast.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_abind_get_dimnames
List rcpp_abind_get_dimnames(List x, int along);
RcppExport SEXP _broadcast_rcpp_abind_get_dimnames(SEXP xSEXP, SEXP alongSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type along(alongSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_abind_get_dimnames(x, along));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_rcbind_get_sizes
IntegerVector rcpp_rcbind_get_sizes(List lst, int imargin);
RcppExport SEXP _broadcast_rcpp_rcbind_get_sizes(SEXP lstSEXP, SEXP imarginSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type lst(lstSEXP);
    Rcpp::traits::input_parameter< int >::type imargin(imarginSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_rcbind_get_sizes(lst, imargin));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_str_dist_led
int rcpp_str_dist_led(String x, String y);
RcppExport SEXP _broadcast_rcpp_str_dist_led(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type x(xSEXP);
    Rcpp::traits::input_parameter< String >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_str_dist_led(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bcDist_str_v
SEXP rcpp_bcDist_str_v(CharacterVector x, CharacterVector y, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bcDist_str_v(SEXP xSEXP, SEXP ySEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bcDist_str_v(x, y, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bcDist_str_ov
SEXP rcpp_bcDist_str_ov(CharacterVector x, CharacterVector y, bool RxC, SEXP out_dim, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bcDist_str_ov(SEXP xSEXP, SEXP ySEXP, SEXP RxCSEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type RxC(RxCSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bcDist_str_ov(x, y, RxC, out_dim, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bcDist_str_bs
SEXP rcpp_bcDist_str_bs(CharacterVector x, CharacterVector y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, bool bigx, int op);
RcppExport SEXP _broadcast_rcpp_bcDist_str_bs(SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP bigxSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< bool >::type bigx(bigxSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bcDist_str_bs(x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, bigx, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bcDist_str_d
SEXP rcpp_bcDist_str_d(CharacterVector x, CharacterVector y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bcDist_str_d(SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bcDist_str_d(x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_cplx_equal
int rcpp_cplx_equal(const Rcomplex& x, const Rcomplex& y);
RcppExport SEXP _broadcast_rcpp_cplx_equal(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcomplex& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcomplex& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_cplx_equal(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_cplx_unequal
int rcpp_cplx_unequal(const Rcomplex& x, const Rcomplex& y);
RcppExport SEXP _broadcast_rcpp_cplx_unequal(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcomplex& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcomplex& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_cplx_unequal(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bcRel_cplx_v
SEXP rcpp_bcRel_cplx_v(SEXP x, SEXP y, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bcRel_cplx_v(SEXP xSEXP, SEXP ySEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bcRel_cplx_v(x, y, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bcRel_cplx_ov
SEXP rcpp_bcRel_cplx_ov(SEXP x, SEXP y, bool RxC, SEXP out_dim, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bcRel_cplx_ov(SEXP xSEXP, SEXP ySEXP, SEXP RxCSEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type RxC(RxCSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bcRel_cplx_ov(x, y, RxC, out_dim, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bcRel_cplx_bs
SEXP rcpp_bcRel_cplx_bs(SEXP x, SEXP y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, bool bigx, int op);
RcppExport SEXP _broadcast_rcpp_bcRel_cplx_bs(SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP bigxSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< bool >::type bigx(bigxSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bcRel_cplx_bs(x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, bigx, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bcRel_cplx_d
SEXP rcpp_bcRel_cplx_d(SEXP x, SEXP y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bcRel_cplx_d(SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bcRel_cplx_d(x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bcRel_dbl_v
SEXP rcpp_bcRel_dbl_v(SEXP x, SEXP y, R_xlen_t nout, int op, double prec);
RcppExport SEXP _broadcast_rcpp_bcRel_dbl_v(SEXP xSEXP, SEXP ySEXP, SEXP noutSEXP, SEXP opSEXP, SEXP precSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    Rcpp::traits::input_parameter< double >::type prec(precSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bcRel_dbl_v(x, y, nout, op, prec));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bcRel_dbl_ov
SEXP rcpp_bcRel_dbl_ov(SEXP x, SEXP y, bool RxC, SEXP out_dim, R_xlen_t nout, int op, double prec);
RcppExport SEXP _broadcast_rcpp_bcRel_dbl_ov(SEXP xSEXP, SEXP ySEXP, SEXP RxCSEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP opSEXP, SEXP precSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type RxC(RxCSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    Rcpp::traits::input_parameter< double >::type prec(precSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bcRel_dbl_ov(x, y, RxC, out_dim, nout, op, prec));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bcRel_dbl_bs
SEXP rcpp_bcRel_dbl_bs(SEXP x, SEXP y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, bool bigx, int op, double prec);
RcppExport SEXP _broadcast_rcpp_bcRel_dbl_bs(SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP bigxSEXP, SEXP opSEXP, SEXP precSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< bool >::type bigx(bigxSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    Rcpp::traits::input_parameter< double >::type prec(precSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bcRel_dbl_bs(x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, bigx, op, prec));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bcRel_dbl_d
SEXP rcpp_bcRel_dbl_d(SEXP x, SEXP y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, int op, double prec);
RcppExport SEXP _broadcast_rcpp_bcRel_dbl_d(SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP opSEXP, SEXP precSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    Rcpp::traits::input_parameter< double >::type prec(precSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bcRel_dbl_d(x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, op, prec));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bcRel_str_v
SEXP rcpp_bcRel_str_v(SEXP x, SEXP y, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bcRel_str_v(SEXP xSEXP, SEXP ySEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bcRel_str_v(x, y, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bcRel_str_ov
SEXP rcpp_bcRel_str_ov(SEXP x, SEXP y, bool RxC, SEXP out_dim, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bcRel_str_ov(SEXP xSEXP, SEXP ySEXP, SEXP RxCSEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type RxC(RxCSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bcRel_str_ov(x, y, RxC, out_dim, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bcRel_str_bs
SEXP rcpp_bcRel_str_bs(SEXP x, SEXP y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, bool bigx, int op);
RcppExport SEXP _broadcast_rcpp_bcRel_str_bs(SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP bigxSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< bool >::type bigx(bigxSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bcRel_str_bs(x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, bigx, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bcRel_str_d
SEXP rcpp_bcRel_str_d(SEXP x, SEXP y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bcRel_str_d(SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bcRel_str_d(x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_isTRUE
bool rcpp_isTRUE(int x);
RcppExport SEXP _broadcast_rcpp_isTRUE(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_isTRUE(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_isFALSE
bool rcpp_isFALSE(int x);
RcppExport SEXP _broadcast_rcpp_isFALSE(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_isFALSE(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_b_v
SEXP rcpp_bc_b_v(SEXP x, SEXP y, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bc_b_v(SEXP xSEXP, SEXP ySEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_b_v(x, y, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_b_ov
SEXP rcpp_bc_b_ov(SEXP x, SEXP y, bool RxC, SEXP out_dim, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bc_b_ov(SEXP xSEXP, SEXP ySEXP, SEXP RxCSEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type RxC(RxCSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_b_ov(x, y, RxC, out_dim, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_b_bs
SEXP rcpp_bc_b_bs(SEXP x, SEXP y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, bool bigx, int op);
RcppExport SEXP _broadcast_rcpp_bc_b_bs(SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP bigxSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< bool >::type bigx(bigxSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_b_bs(x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, bigx, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_b_d
SEXP rcpp_bc_b_d(SEXP x, SEXP y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bc_b_d(SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_b_d(x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_bind
void rcpp_bc_bind(SEXP out, SEXP x, SEXP starts, SEXP ends, SEXP by_x, SEXP dimcumprod_out, SEXP dimcumprod_x, SEXP out_dim);
RcppExport SEXP _broadcast_rcpp_bc_bind(SEXP outSEXP, SEXP xSEXP, SEXP startsSEXP, SEXP endsSEXP, SEXP by_xSEXP, SEXP dimcumprod_outSEXP, SEXP dimcumprod_xSEXP, SEXP out_dimSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type out(outSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ends(endsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dimcumprod_out(dimcumprod_outSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dimcumprod_x(dimcumprod_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    rcpp_bc_bind(out, x, starts, ends, by_x, dimcumprod_out, dimcumprod_x, out_dim);
    return R_NilValue;
END_RCPP
}
// rcpp_cplx_plus
Rcomplex rcpp_cplx_plus(const Rcomplex& x, const Rcomplex& y);
RcppExport SEXP _broadcast_rcpp_cplx_plus(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcomplex& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcomplex& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_cplx_plus(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_cplx_min
Rcomplex rcpp_cplx_min(const Rcomplex& x, const Rcomplex& y);
RcppExport SEXP _broadcast_rcpp_cplx_min(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcomplex& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcomplex& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_cplx_min(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_cplx_mult
Rcomplex rcpp_cplx_mult(const Rcomplex& x, const Rcomplex& y);
RcppExport SEXP _broadcast_rcpp_cplx_mult(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcomplex& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcomplex& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_cplx_mult(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_cplx_div
Rcomplex rcpp_cplx_div(const Rcomplex& x, const Rcomplex& y);
RcppExport SEXP _broadcast_rcpp_cplx_div(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcomplex& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcomplex& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_cplx_div(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_cplx_v
SEXP rcpp_bc_cplx_v(SEXP x, SEXP y, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bc_cplx_v(SEXP xSEXP, SEXP ySEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_cplx_v(x, y, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_cplx_ov
SEXP rcpp_bc_cplx_ov(SEXP x, SEXP y, bool RxC, SEXP out_dim, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bc_cplx_ov(SEXP xSEXP, SEXP ySEXP, SEXP RxCSEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type RxC(RxCSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_cplx_ov(x, y, RxC, out_dim, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_cplx_bs
SEXP rcpp_bc_cplx_bs(SEXP x, SEXP y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, bool bigx, int op);
RcppExport SEXP _broadcast_rcpp_bc_cplx_bs(SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP bigxSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< bool >::type bigx(bigxSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_cplx_bs(x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, bigx, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_cplx_d
SEXP rcpp_bc_cplx_d(SEXP x, SEXP y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bc_cplx_d(SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_cplx_d(x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_mod_longint
double rcpp_mod_longint(double x, double y);
RcppExport SEXP _broadcast_rcpp_mod_longint(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_mod_longint(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_dbl_v
SEXP rcpp_bc_dbl_v(SEXP x, SEXP y, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bc_dbl_v(SEXP xSEXP, SEXP ySEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_dbl_v(x, y, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_dbl_ov
SEXP rcpp_bc_dbl_ov(SEXP x, SEXP y, bool RxC, SEXP out_dim, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bc_dbl_ov(SEXP xSEXP, SEXP ySEXP, SEXP RxCSEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type RxC(RxCSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_dbl_ov(x, y, RxC, out_dim, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_dbl_bs
SEXP rcpp_bc_dbl_bs(SEXP x, SEXP y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, bool bigx, int op);
RcppExport SEXP _broadcast_rcpp_bc_dbl_bs(SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP bigxSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< bool >::type bigx(bigxSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_dbl_bs(x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, bigx, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_dbl_d
SEXP rcpp_bc_dbl_d(SEXP x, SEXP y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bc_dbl_d(SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_dbl_d(x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_cplx_returnNA
Rcomplex rcpp_cplx_returnNA();
RcppExport SEXP _broadcast_rcpp_cplx_returnNA() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_cplx_returnNA());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_ifelse_v
SEXP rcpp_bc_ifelse_v(SEXP cond, SEXP x, SEXP y, R_xlen_t nout);
RcppExport SEXP _broadcast_rcpp_bc_ifelse_v(SEXP condSEXP, SEXP xSEXP, SEXP ySEXP, SEXP noutSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type cond(condSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_ifelse_v(cond, x, y, nout));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_ifelse_ov
SEXP rcpp_bc_ifelse_ov(SEXP cond, SEXP x, SEXP y, bool RxC, SEXP out_dim, R_xlen_t nout);
RcppExport SEXP _broadcast_rcpp_bc_ifelse_ov(SEXP condSEXP, SEXP xSEXP, SEXP ySEXP, SEXP RxCSEXP, SEXP out_dimSEXP, SEXP noutSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type cond(condSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type RxC(RxCSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_ifelse_ov(cond, x, y, RxC, out_dim, nout));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_ifelse_bs
SEXP rcpp_bc_ifelse_bs(SEXP cond, SEXP x, SEXP y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, bool bigx);
RcppExport SEXP _broadcast_rcpp_bc_ifelse_bs(SEXP condSEXP, SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP bigxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type cond(condSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< bool >::type bigx(bigxSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_ifelse_bs(cond, x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, bigx));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_ifelse_d
SEXP rcpp_bc_ifelse_d(SEXP cond, SEXP x, SEXP y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout);
RcppExport SEXP _broadcast_rcpp_bc_ifelse_d(SEXP condSEXP, SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type cond(condSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_ifelse_d(cond, x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_list_v
SEXP rcpp_bc_list_v(List x, List y, R_xlen_t nout, Function f);
RcppExport SEXP _broadcast_rcpp_bc_list_v(SEXP xSEXP, SEXP ySEXP, SEXP noutSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< List >::type y(ySEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_list_v(x, y, nout, f));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_list_ov
SEXP rcpp_bc_list_ov(List x, List y, bool RxC, SEXP out_dim, R_xlen_t nout, Function f);
RcppExport SEXP _broadcast_rcpp_bc_list_ov(SEXP xSEXP, SEXP ySEXP, SEXP RxCSEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< List >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type RxC(RxCSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_list_ov(x, y, RxC, out_dim, nout, f));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_list_bs
SEXP rcpp_bc_list_bs(List x, List y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, bool bigx, Function f);
RcppExport SEXP _broadcast_rcpp_bc_list_bs(SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP bigxSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< List >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< bool >::type bigx(bigxSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_list_bs(x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, bigx, f));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_list_d
SEXP rcpp_bc_list_d(List x, List y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, Function f);
RcppExport SEXP _broadcast_rcpp_bc_list_d(SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< List >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_list_d(x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, f));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_string_plus
String rcpp_string_plus(String x, String y);
RcppExport SEXP _broadcast_rcpp_string_plus(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type x(xSEXP);
    Rcpp::traits::input_parameter< String >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_string_plus(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_str_v
SEXP rcpp_bc_str_v(CharacterVector x, CharacterVector y, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bc_str_v(SEXP xSEXP, SEXP ySEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_str_v(x, y, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_str_ov
SEXP rcpp_bc_str_ov(CharacterVector x, CharacterVector y, bool RxC, SEXP out_dim, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bc_str_ov(SEXP xSEXP, SEXP ySEXP, SEXP RxCSEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type RxC(RxCSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_str_ov(x, y, RxC, out_dim, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_str_bs
SEXP rcpp_bc_str_bs(CharacterVector x, CharacterVector y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, bool bigx, int op);
RcppExport SEXP _broadcast_rcpp_bc_str_bs(SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP bigxSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< bool >::type bigx(bigxSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_str_bs(x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, bigx, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bc_str_d
SEXP rcpp_bc_str_d(CharacterVector x, CharacterVector y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, int op);
RcppExport SEXP _broadcast_rcpp_bc_str_d(SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bc_str_d(x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, op));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bcapply_v
void rcpp_bcapply_v(SEXP out, SEXP x, SEXP y, R_xlen_t nout, Function f);
RcppExport SEXP _broadcast_rcpp_bcapply_v(SEXP outSEXP, SEXP xSEXP, SEXP ySEXP, SEXP noutSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type out(outSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    rcpp_bcapply_v(out, x, y, nout, f);
    return R_NilValue;
END_RCPP
}
// rcpp_bcapply_ov
void rcpp_bcapply_ov(SEXP out, SEXP x, SEXP y, bool RxC, SEXP out_dim, R_xlen_t nout, Function f);
RcppExport SEXP _broadcast_rcpp_bcapply_ov(SEXP outSEXP, SEXP xSEXP, SEXP ySEXP, SEXP RxCSEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type out(outSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type RxC(RxCSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    rcpp_bcapply_ov(out, x, y, RxC, out_dim, nout, f);
    return R_NilValue;
END_RCPP
}
// rcpp_bcapply_bs
void rcpp_bcapply_bs(SEXP out, SEXP x, SEXP y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, bool bigx, Function f);
RcppExport SEXP _broadcast_rcpp_bcapply_bs(SEXP outSEXP, SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP bigxSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type out(outSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< bool >::type bigx(bigxSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    rcpp_bcapply_bs(out, x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, bigx, f);
    return R_NilValue;
END_RCPP
}
// rcpp_bcapply_d
void rcpp_bcapply_d(SEXP out, SEXP x, SEXP y, SEXP by_x, SEXP by_y, SEXP dcp_x, SEXP dcp_y, SEXP out_dim, R_xlen_t nout, Function f);
RcppExport SEXP _broadcast_rcpp_bcapply_d(SEXP outSEXP, SEXP xSEXP, SEXP ySEXP, SEXP by_xSEXP, SEXP by_ySEXP, SEXP dcp_xSEXP, SEXP dcp_ySEXP, SEXP out_dimSEXP, SEXP noutSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type out(outSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_x(by_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_y(by_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_x(dcp_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcp_y(dcp_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dim(out_dimSEXP);
    Rcpp::traits::input_parameter< R_xlen_t >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    rcpp_bcapply_d(out, x, y, by_x, by_y, dcp_x, dcp_y, out_dim, nout, f);
    return R_NilValue;
END_RCPP
}
// rcpp_bindhelper_max_type
int rcpp_bindhelper_max_type(SEXP x);
RcppExport SEXP _broadcast_rcpp_bindhelper_max_type(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bindhelper_max_type(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bindhelper_vdims
SEXP rcpp_bindhelper_vdims(SEXP x);
RcppExport SEXP _broadcast_rcpp_bindhelper_vdims(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bindhelper_vdims(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bindhelper_neednorm
SEXP rcpp_bindhelper_neednorm(SEXP x, int target_dimlen);
RcppExport SEXP _broadcast_rcpp_bindhelper_neednorm(SEXP xSEXP, SEXP target_dimlenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type target_dimlen(target_dimlenSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bindhelper_neednorm(x, target_dimlen));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bindhelper_sum_along
R_xlen_t rcpp_bindhelper_sum_along(SEXP lst_dims, int along);
RcppExport SEXP _broadcast_rcpp_bindhelper_sum_along(SEXP lst_dimsSEXP, SEXP alongSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type lst_dims(lst_dimsSEXP);
    Rcpp::traits::input_parameter< int >::type along(alongSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bindhelper_sum_along(lst_dims, along));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bindhelper_conf_dims_2
bool rcpp_bindhelper_conf_dims_2(SEXP x, SEXP y, int along, int max_bc);
RcppExport SEXP _broadcast_rcpp_bindhelper_conf_dims_2(SEXP xSEXP, SEXP ySEXP, SEXP alongSEXP, SEXP max_bcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type along(alongSEXP);
    Rcpp::traits::input_parameter< int >::type max_bc(max_bcSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bindhelper_conf_dims_2(x, y, along, max_bc));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_bindhelper_conf_dims_all
bool rcpp_bindhelper_conf_dims_all(SEXP lst_dims, SEXP target, int along, int max_bc);
RcppExport SEXP _broadcast_rcpp_bindhelper_conf_dims_all(SEXP lst_dimsSEXP, SEXP targetSEXP, SEXP alongSEXP, SEXP max_bcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type lst_dims(lst_dimsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type target(targetSEXP);
    Rcpp::traits::input_parameter< int >::type along(alongSEXP);
    Rcpp::traits::input_parameter< int >::type max_bc(max_bcSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_bindhelper_conf_dims_all(lst_dims, target, along, max_bc));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_recycle_seq_mlen
List rcpp_recycle_seq_mlen(IntegerVector x, IntegerVector y);
RcppExport SEXP _broadcast_rcpp_recycle_seq_mlen(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_recycle_seq_mlen(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_set_vind_32_atomic
void rcpp_set_vind_32_atomic(SEXP x, const SEXP ind, const SEXP rp);
RcppExport SEXP _broadcast_rcpp_set_vind_32_atomic(SEXP xSEXP, SEXP indSEXP, SEXP rpSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type ind(indSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type rp(rpSEXP);
    rcpp_set_vind_32_atomic(x, ind, rp);
    return R_NilValue;
END_RCPP
}
// rcpp_set_vind_64_atomic
void rcpp_set_vind_64_atomic(SEXP x, const SEXP ind, const SEXP rp);
RcppExport SEXP _broadcast_rcpp_set_vind_64_atomic(SEXP xSEXP, SEXP indSEXP, SEXP rpSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type ind(indSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type rp(rpSEXP);
    rcpp_set_vind_64_atomic(x, ind, rp);
    return R_NilValue;
END_RCPP
}

RcppExport SEXP C_any_nonNULL(SEXP);
RcppExport SEXP C_check_conf_dim(SEXP, SEXP);
RcppExport SEXP C_dims_all_orthogonal(SEXP, SEXP);
RcppExport SEXP C_findfirst_mergable_dims(SEXP, SEXP);
RcppExport SEXP C_pmax(SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_broadcast_rcpp_abind_get_dimnames", (DL_FUNC) &_broadcast_rcpp_abind_get_dimnames, 2},
    {"_broadcast_rcpp_rcbind_get_sizes", (DL_FUNC) &_broadcast_rcpp_rcbind_get_sizes, 2},
    {"_broadcast_rcpp_str_dist_led", (DL_FUNC) &_broadcast_rcpp_str_dist_led, 2},
    {"_broadcast_rcpp_bcDist_str_v", (DL_FUNC) &_broadcast_rcpp_bcDist_str_v, 4},
    {"_broadcast_rcpp_bcDist_str_ov", (DL_FUNC) &_broadcast_rcpp_bcDist_str_ov, 6},
    {"_broadcast_rcpp_bcDist_str_bs", (DL_FUNC) &_broadcast_rcpp_bcDist_str_bs, 10},
    {"_broadcast_rcpp_bcDist_str_d", (DL_FUNC) &_broadcast_rcpp_bcDist_str_d, 9},
    {"_broadcast_rcpp_cplx_equal", (DL_FUNC) &_broadcast_rcpp_cplx_equal, 2},
    {"_broadcast_rcpp_cplx_unequal", (DL_FUNC) &_broadcast_rcpp_cplx_unequal, 2},
    {"_broadcast_rcpp_bcRel_cplx_v", (DL_FUNC) &_broadcast_rcpp_bcRel_cplx_v, 4},
    {"_broadcast_rcpp_bcRel_cplx_ov", (DL_FUNC) &_broadcast_rcpp_bcRel_cplx_ov, 6},
    {"_broadcast_rcpp_bcRel_cplx_bs", (DL_FUNC) &_broadcast_rcpp_bcRel_cplx_bs, 10},
    {"_broadcast_rcpp_bcRel_cplx_d", (DL_FUNC) &_broadcast_rcpp_bcRel_cplx_d, 9},
    {"_broadcast_rcpp_bcRel_dbl_v", (DL_FUNC) &_broadcast_rcpp_bcRel_dbl_v, 5},
    {"_broadcast_rcpp_bcRel_dbl_ov", (DL_FUNC) &_broadcast_rcpp_bcRel_dbl_ov, 7},
    {"_broadcast_rcpp_bcRel_dbl_bs", (DL_FUNC) &_broadcast_rcpp_bcRel_dbl_bs, 11},
    {"_broadcast_rcpp_bcRel_dbl_d", (DL_FUNC) &_broadcast_rcpp_bcRel_dbl_d, 10},
    {"_broadcast_rcpp_bcRel_str_v", (DL_FUNC) &_broadcast_rcpp_bcRel_str_v, 4},
    {"_broadcast_rcpp_bcRel_str_ov", (DL_FUNC) &_broadcast_rcpp_bcRel_str_ov, 6},
    {"_broadcast_rcpp_bcRel_str_bs", (DL_FUNC) &_broadcast_rcpp_bcRel_str_bs, 10},
    {"_broadcast_rcpp_bcRel_str_d", (DL_FUNC) &_broadcast_rcpp_bcRel_str_d, 9},
    {"_broadcast_rcpp_isTRUE", (DL_FUNC) &_broadcast_rcpp_isTRUE, 1},
    {"_broadcast_rcpp_isFALSE", (DL_FUNC) &_broadcast_rcpp_isFALSE, 1},
    {"_broadcast_rcpp_bc_b_v", (DL_FUNC) &_broadcast_rcpp_bc_b_v, 4},
    {"_broadcast_rcpp_bc_b_ov", (DL_FUNC) &_broadcast_rcpp_bc_b_ov, 6},
    {"_broadcast_rcpp_bc_b_bs", (DL_FUNC) &_broadcast_rcpp_bc_b_bs, 10},
    {"_broadcast_rcpp_bc_b_d", (DL_FUNC) &_broadcast_rcpp_bc_b_d, 9},
    {"_broadcast_rcpp_bc_bind", (DL_FUNC) &_broadcast_rcpp_bc_bind, 8},
    {"_broadcast_rcpp_cplx_plus", (DL_FUNC) &_broadcast_rcpp_cplx_plus, 2},
    {"_broadcast_rcpp_cplx_min", (DL_FUNC) &_broadcast_rcpp_cplx_min, 2},
    {"_broadcast_rcpp_cplx_mult", (DL_FUNC) &_broadcast_rcpp_cplx_mult, 2},
    {"_broadcast_rcpp_cplx_div", (DL_FUNC) &_broadcast_rcpp_cplx_div, 2},
    {"_broadcast_rcpp_bc_cplx_v", (DL_FUNC) &_broadcast_rcpp_bc_cplx_v, 4},
    {"_broadcast_rcpp_bc_cplx_ov", (DL_FUNC) &_broadcast_rcpp_bc_cplx_ov, 6},
    {"_broadcast_rcpp_bc_cplx_bs", (DL_FUNC) &_broadcast_rcpp_bc_cplx_bs, 10},
    {"_broadcast_rcpp_bc_cplx_d", (DL_FUNC) &_broadcast_rcpp_bc_cplx_d, 9},
    {"_broadcast_rcpp_mod_longint", (DL_FUNC) &_broadcast_rcpp_mod_longint, 2},
    {"_broadcast_rcpp_bc_dbl_v", (DL_FUNC) &_broadcast_rcpp_bc_dbl_v, 4},
    {"_broadcast_rcpp_bc_dbl_ov", (DL_FUNC) &_broadcast_rcpp_bc_dbl_ov, 6},
    {"_broadcast_rcpp_bc_dbl_bs", (DL_FUNC) &_broadcast_rcpp_bc_dbl_bs, 10},
    {"_broadcast_rcpp_bc_dbl_d", (DL_FUNC) &_broadcast_rcpp_bc_dbl_d, 9},
    {"_broadcast_rcpp_cplx_returnNA", (DL_FUNC) &_broadcast_rcpp_cplx_returnNA, 0},
    {"_broadcast_rcpp_bc_ifelse_v", (DL_FUNC) &_broadcast_rcpp_bc_ifelse_v, 4},
    {"_broadcast_rcpp_bc_ifelse_ov", (DL_FUNC) &_broadcast_rcpp_bc_ifelse_ov, 6},
    {"_broadcast_rcpp_bc_ifelse_bs", (DL_FUNC) &_broadcast_rcpp_bc_ifelse_bs, 10},
    {"_broadcast_rcpp_bc_ifelse_d", (DL_FUNC) &_broadcast_rcpp_bc_ifelse_d, 9},
    {"_broadcast_rcpp_bc_list_v", (DL_FUNC) &_broadcast_rcpp_bc_list_v, 4},
    {"_broadcast_rcpp_bc_list_ov", (DL_FUNC) &_broadcast_rcpp_bc_list_ov, 6},
    {"_broadcast_rcpp_bc_list_bs", (DL_FUNC) &_broadcast_rcpp_bc_list_bs, 10},
    {"_broadcast_rcpp_bc_list_d", (DL_FUNC) &_broadcast_rcpp_bc_list_d, 9},
    {"_broadcast_rcpp_string_plus", (DL_FUNC) &_broadcast_rcpp_string_plus, 2},
    {"_broadcast_rcpp_bc_str_v", (DL_FUNC) &_broadcast_rcpp_bc_str_v, 4},
    {"_broadcast_rcpp_bc_str_ov", (DL_FUNC) &_broadcast_rcpp_bc_str_ov, 6},
    {"_broadcast_rcpp_bc_str_bs", (DL_FUNC) &_broadcast_rcpp_bc_str_bs, 10},
    {"_broadcast_rcpp_bc_str_d", (DL_FUNC) &_broadcast_rcpp_bc_str_d, 9},
    {"_broadcast_rcpp_bcapply_v", (DL_FUNC) &_broadcast_rcpp_bcapply_v, 5},
    {"_broadcast_rcpp_bcapply_ov", (DL_FUNC) &_broadcast_rcpp_bcapply_ov, 7},
    {"_broadcast_rcpp_bcapply_bs", (DL_FUNC) &_broadcast_rcpp_bcapply_bs, 11},
    {"_broadcast_rcpp_bcapply_d", (DL_FUNC) &_broadcast_rcpp_bcapply_d, 10},
    {"_broadcast_rcpp_bindhelper_max_type", (DL_FUNC) &_broadcast_rcpp_bindhelper_max_type, 1},
    {"_broadcast_rcpp_bindhelper_vdims", (DL_FUNC) &_broadcast_rcpp_bindhelper_vdims, 1},
    {"_broadcast_rcpp_bindhelper_neednorm", (DL_FUNC) &_broadcast_rcpp_bindhelper_neednorm, 2},
    {"_broadcast_rcpp_bindhelper_sum_along", (DL_FUNC) &_broadcast_rcpp_bindhelper_sum_along, 2},
    {"_broadcast_rcpp_bindhelper_conf_dims_2", (DL_FUNC) &_broadcast_rcpp_bindhelper_conf_dims_2, 4},
    {"_broadcast_rcpp_bindhelper_conf_dims_all", (DL_FUNC) &_broadcast_rcpp_bindhelper_conf_dims_all, 4},
    {"_broadcast_rcpp_recycle_seq_mlen", (DL_FUNC) &_broadcast_rcpp_recycle_seq_mlen, 2},
    {"_broadcast_rcpp_set_vind_32_atomic", (DL_FUNC) &_broadcast_rcpp_set_vind_32_atomic, 3},
    {"_broadcast_rcpp_set_vind_64_atomic", (DL_FUNC) &_broadcast_rcpp_set_vind_64_atomic, 3},
    {"C_any_nonNULL",             (DL_FUNC) &C_any_nonNULL,             1},
    {"C_check_conf_dim",          (DL_FUNC) &C_check_conf_dim,          2},
    {"C_dims_all_orthogonal",     (DL_FUNC) &C_dims_all_orthogonal,     2},
    {"C_findfirst_mergable_dims", (DL_FUNC) &C_findfirst_mergable_dims, 2},
    {"C_pmax",                    (DL_FUNC) &C_pmax,                    2},
    {NULL, NULL, 0}
};

RcppExport void R_init_broadcast(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
