# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
.rcpp_test <- function(x, y) {
    .Call(`_broadcast_rcpp_test`, x, y)
}

#' @keywords internal
#' @noRd
.rcpp_bc_dbl_v <- function(x, y, nout, op) {
    .Call(`_broadcast_rcpp_bc_dbl_v`, x, y, nout, op)
}

#' @keywords internal
#' @noRd
.rcpp_bc_dbl_d <- function(x, y, by_x, by_y, dimcumprod_x, dimcumprod_y, out_dim, nout, op) {
    .Call(`_broadcast_rcpp_bc_dbl_d`, x, y, by_x, by_y, dimcumprod_x, dimcumprod_y, out_dim, nout, op)
}

#' @keywords internal
#' @noRd
.rcpp_bc_dbl_general <- function(x, y, s1, s2, xdims1, xdims2, nout, op) {
    .Call(`_broadcast_rcpp_bc_dbl_general`, x, y, s1, s2, xdims1, xdims2, nout, op)
}

#' @keywords internal
#' @noRd
.rcpp_seq_mlen <- function(x) {
    .Call(`_broadcast_rcpp_seq_mlen`, x)
}

#' @keywords internal
#' @noRd
.rcpp_recycle_seq_mlen <- function(x, y) {
    .Call(`_broadcast_rcpp_recycle_seq_mlen`, x, y)
}

