# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' @noRd
.rcpp_bcRel_dbl_v <- function(x, y, nout, op, prec) {
    .Call(`_broadcast_rcpp_bcRel_dbl_v`, x, y, nout, op, prec)
}

#' @keywords internal
#' @noRd
.rcpp_bcRel_dbl_ov <- function(x, y, RxC, out_dim, nout, op, prec) {
    .Call(`_broadcast_rcpp_bcRel_dbl_ov`, x, y, RxC, out_dim, nout, op, prec)
}

#' @keywords internal
#' @noRd
.rcpp_bcRel_dbl_bs <- function(x, y, by_x, by_y, dimcumprod_x, dimcumprod_y, out_dim, nout, bigx, op, prec) {
    .Call(`_broadcast_rcpp_bcRel_dbl_bs`, x, y, by_x, by_y, dimcumprod_x, dimcumprod_y, out_dim, nout, bigx, op, prec)
}

#' @keywords internal
#' @noRd
.rcpp_bcRel_dbl_d <- function(x, y, by_x, by_y, dimcumprod_x, dimcumprod_y, out_dim, nout, op, prec) {
    .Call(`_broadcast_rcpp_bcRel_dbl_d`, x, y, by_x, by_y, dimcumprod_x, dimcumprod_y, out_dim, nout, op, prec)
}

#' @keywords internal
#' @noRd
.rcpp_bc_dbl_v <- function(x, y, nout, op) {
    .Call(`_broadcast_rcpp_bc_dbl_v`, x, y, nout, op)
}

#' @keywords internal
#' @noRd
.rcpp_bc_dbl_ov <- function(x, y, RxC, out_dim, nout, op) {
    .Call(`_broadcast_rcpp_bc_dbl_ov`, x, y, RxC, out_dim, nout, op)
}

#' @keywords internal
#' @noRd
.rcpp_bc_dbl_bs <- function(x, y, by_x, by_y, dimcumprod_x, dimcumprod_y, out_dim, nout, bigx, op) {
    .Call(`_broadcast_rcpp_bc_dbl_bs`, x, y, by_x, by_y, dimcumprod_x, dimcumprod_y, out_dim, nout, bigx, op)
}

#' @keywords internal
#' @noRd
.rcpp_bc_dbl_d <- function(x, y, by_x, by_y, dimcumprod_x, dimcumprod_y, out_dim, nout, op) {
    .Call(`_broadcast_rcpp_bc_dbl_d`, x, y, by_x, by_y, dimcumprod_x, dimcumprod_y, out_dim, nout, op)
}

#' @keywords internal
#' @noRd
.rcpp_seq_mlen <- function(x) {
    .Call(`_broadcast_rcpp_seq_mlen`, x)
}

#' @keywords internal
#' @noRd
.rcpp_recycle_seq_mlen <- function(x, y) {
    .Call(`_broadcast_rcpp_recycle_seq_mlen`, x, y)
}

